<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fullrecall [
	<!ELEMENT fullrecall (category?)>
	<!ELEMENT category (item?)>
	<!ELEMENT item (q, a)>
	<!ELEMENT q (#PCDATA)>
	<!ELEMENT a (#PCDATA)>
	<!ATTLIST fullrecall core_version CDATA #IMPLIED
		time_of_start CDATA #REQUIRED>
	<!ATTLIST category name CDATA #REQUIRED
		qbgclr CDATA #IMPLIED
		abgclr CDATA #IMPLIED
		qfntclr CDATA #IMPLIED
		afntclr CDATA #IMPLIED
		qfont CDATA #IMPLIED
		afont CDATA #IMPLIED
		qimg CDATA #IMPLIED
		aimg CDATA #IMPLIED>
	<!ATTLIST item id ID #REQUIRED
		tmtrpt CDATA #REQUIRED
		stmtrpt CDATA #REQUIRED
		llivl CDATA #REQUIRED
		rlivl CDATA #REQUIRED
		ivl CDATA #REQUIRED
		rp CDATA #REQUIRED
		gr CDATA #REQUIRED
		sstick IDREF #IMPLIED
		hstick IDREF #IMPLIED>
]>

<!--
FullRecall saves both elements.bin (space and speed efficient format)
and elements.xml (this file contains the same data in human-readable XML format)
FullRecall reads this file instead of elements.bin if either elements.bin is unavailable
or this file was modified more recently than elements.bin

LEGEND:
 time_of_start = first day of your FullRecall learning (in Unix time format)
 ITEM DATA:
  id  = id number (in fact: time of creating item in Unix time format)
  tmtrpt  = time to repeat
  stmtrpt = time to repeat computed on not-ahead-of-scheduled-time review
  livl= last interval computed by ANN (in days; 0-2048)
  rllivl  = real last interval (in days; 0-2048)
  ivl = interval (in days; 0-2048)
  rp  = number of not-ahead-of-scheduled-time reviews (0-128)
  gr  = grade (0-5; 0=the worst, 5=the best)
  q   = question
  a   = answer
-->


<fullrecall core_version="12" time_of_start="1487152617">

<category name="root">

</category>

<category name="English">

<item id="1487339781" tmtrpt="4" stmtrpt="4" livl="0" rllivl="0" ivl="2" rp="0" gr="4">
<q>provision</q>
<a>zaopatrzenie</a>
</item>

<item id="1487439949" tmtrpt="5" stmtrpt="5" livl="0" rllivl="0" ivl="2" rp="0" gr="4">
<q>how to create group in linux?</q>
<a><![CDATA[groupadd <name>]]></a>
</item>

<item id="1487439978" tmtrpt="5" stmtrpt="5" livl="0" rllivl="0" ivl="2" rp="0" gr="4">
<q>How to modify user in linux?</q>
<a>usermod</a>
</item>

</category>

<category name="Work">

<category name="phpStorm">

<item id="1487322734" tmtrpt="6" stmtrpt="6" livl="0" rllivl="0" ivl="4" rp="0" gr="5">
<q>Go to settings phpStorm</q>
<a>Ctrl+Alt+S

S Settings</a>
</item>

<item id="1487255060" tmtrpt="10" stmtrpt="3" livl="2" rllivl="1" ivl="8" rp="0" gr="4">
<q>phpStorm 
How to navigate to class, file, symbol?</q>
<a>class -> Ctrl+N
file -> Ctrl+Shift+N
symbol -> Ctrl+Shift+Alt+N

N as Name</a>
</item>

</category>

<item id="1487230473" tmtrpt="2" stmtrpt="2" livl="0" rllivl="0" ivl="1" rp="0" gr="3">
<q>image for   _</q>
<a>wózek widłowy</a>
</item>

<item id="1487324098" tmtrpt="2" stmtrpt="2" livl="0" rllivl="0" ivl="0" rp="0" gr="2">
<q>docker run command 

How it looks like?

example  for bash



</q>
<a>docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

docker run -t -i --rm ubuntu bash</a>
</item>

<item id="1487324990" tmtrpt="2" stmtrpt="2" livl="0" rllivl="0" ivl="0" rp="0" gr="2">
<q>structure for refresh-availability -L 1</q>
<a>|-- Dockerfile.consumer
|-- Dockerfile.producer
|-- Dockerfile.rabbitmq
|-- README.md
|-- app
|   |-- bootstrap.php
|   `-- config.php
|-- composer.json
|-- composer.lock
|-- config
|   `-- config.ini
|-- console.php
|-- docker-compose.yml
|-- src
|   `-- RefreshAvailability
|       |-- Command
|       |   |-- AbstractCommand.php
|       |   |-- ConsumerCommand.php
|       |   `-- ProducerCommand.php
|       |-- Model
|       |   |-- Message.php
|       |   `-- Variant.php
|       `-- Persistence
|           `-- InMemoryServiceRepository.php
`-- vendor</a>
</item>

<item id="1487325739" tmtrpt="3" stmtrpt="3" livl="0" rllivl="0" ivl="1" rp="0" gr="3">
<q>docker-compose  rebuild only one container ?</q>
<a>docker-compose stop web
docker-compose build web
docker-compose up -d --no-deps web</a>
</item>

<item id="1487339763" tmtrpt="3" stmtrpt="3" livl="0" rllivl="0" ivl="1" rp="0" gr="3">
<q>How to copy file from container to host?</q>
<a><![CDATA[docker cp <containerId>:/file/path/within/container /host/path/target]]></a>
</item>

<item id="1487316655" tmtrpt="4" stmtrpt="4" livl="0" rllivl="0" ivl="2" rp="0" gr="4">
<q>Which sap-webservices we are using in refresh-availability script?</q>
<a>Z_WEB_AV_STOCK -> how much stuff is in a warehouse
Z_WEB_AV_STATUS 
Z_WEB_AV_SUPPLIER</a>
</item>

<item id="1487316795" tmtrpt="4" stmtrpt="4" livl="0" rllivl="0" ivl="2" rp="0" gr="4">
<q>memory image
SAP </q>
<a>sapiący koleś</a>
</item>

<item id="1487316930" tmtrpt="4" stmtrpt="4" livl="0" rllivl="0" ivl="2" rp="0" gr="4">
<q>memory img

refresh-availability</q>
<a><![CDATA[Tutaj wpisz odpowiedź.<img>imgs\refresh-availability_odświeżacz.jpg</img>]]></a>
</item>

<item id="1487325836" tmtrpt="4" stmtrpt="4" livl="0" rllivl="0" ivl="2" rp="0" gr="4">
<q>How to run docker container in detached mode 
in background</q>
<a><![CDATA[docker-compose up -d 

<b>-d</b>]]></a>
</item>

<item id="1487234750" tmtrpt="6" stmtrpt="3" livl="2" rllivl="1" ivl="4" rp="0" gr="3">
<q>Which command stop docker container?</q>
<a><![CDATA[docker stop   -> gracefuly
docker kill    -> 
docker rm -f  -> force option<img>imgs\docker_image.png</img>]]></a>
</item>

<item id="1487253565" tmtrpt="6" stmtrpt="3" livl="2" rllivl="1" ivl="4" rp="0" gr="3">
<q>Test REC schema</q>
<a>


IWMTNEW_T2
Im Więcej Miejsca Tym NEW Telewizor 2</a>
</item>

<item id="1487230229" tmtrpt="8" stmtrpt="8" livl="1" rllivl="1" ivl="6" rp="1" gr="4">
<q>Ending of elastic kopf plugin?</q>
<a>/_plugin/kopf</a>
</item>

<item id="1487253503" tmtrpt="10" stmtrpt="3" livl="2" rllivl="1" ivl="8" rp="0" gr="4">
<q>Where we keep information about reservations?
schema, table</q>
<a>IWMTNEW_T2 
availability
</a>
</item>

<item id="1487232861" tmtrpt="13" stmtrpt="3" livl="2" rllivl="1" ivl="11" rp="0" gr="5">
<q>default ES port </q>
<a>PaNSoS
9200
</a>
</item>

<item id="1487233729" tmtrpt="14" stmtrpt="3" livl="2" rllivl="1" ivl="12" rp="0" gr="5">
<q>What labels are in docker-composer?</q>
<a><![CDATA[They add metadata to containers
https://docs.docker.com/engine/userguide/labels-custom-metadata/<img>imgs\docker_image.png</img>]]></a>
</item>

<item id="1487243296" tmtrpt="15" stmtrpt="3" livl="13" rllivl="0" ivl="13" rp="0" gr="4">
<q>numer do szefa 9express</q>
<a>60 61 62 60 1
jazz yetti cyna jazz duch
</a>
</item>

<item id="1487232176" tmtrpt="16" stmtrpt="3" livl="2" rllivl="1" ivl="14" rp="0" gr="5">
<q>images for slash   \   and   /</q>
<a><![CDATA[<img>imgs\slash-backslash.png</img>]]></a>
</item>

</category>

<category name="Home">

</category>

</fullrecall>